export const TYPE_KO: Record<string, string> = {
  NORMAL: "노말",
  FIRE: "불꽃",
  WATER: "물",
  GRASS: "풀",
  ELECTRIC: "전기",
  ICE: "얼음",
  FIGHTING: "격투",
  POISON: "독",
  GROUND: "땅",
  FLYING: "비행",
  PSYCHIC: "에스퍼",
  BUG: "벌레",
  ROCK: "바위",
  GHOST: "고스트",
  DRAGON: "드래곤",
  DARK: "악",
  STEEL: "강철",
  FAIRY: "페어리",
};

export function typeQueryHit(types: string | string[], typeFilter: string, q: string) {
  const list = Array.isArray(types) ? types : [types];
  if (typeFilter && !list.includes(typeFilter)) return false;
  if (!q) return true;
  return list.some((t) => t.toLowerCase().includes(q) || (TYPE_KO[t] || "").includes(q));
}

export const TYPE_TONE: Record<string, string> = {
  NORMAL: "var(--type-normal)",
  FIRE: "var(--type-fire)",
  WATER: "var(--type-water)",
  GRASS: "var(--type-grass)",
  ELECTRIC: "var(--type-electric)",
  ICE: "var(--type-ice)",
  FIGHTING: "var(--type-fighting)",
  POISON: "var(--type-poison)",
  GROUND: "var(--type-ground)",
  FLYING: "var(--type-flying)",
  PSYCHIC: "var(--type-psychic)",
  BUG: "var(--type-bug)",
  ROCK: "var(--type-rock)",
  GHOST: "var(--type-ghost)",
  DRAGON: "var(--type-dragon)",
  DARK: "var(--type-dark)",
  STEEL: "var(--type-steel)",
  FAIRY: "var(--type-fairy)",
};

export const STAT_LABELS = [
  { key: "hp" as const, label: "HP" },
  { key: "atk" as const, label: "공격" },
  { key: "def" as const, label: "방어" },
  { key: "spa" as const, label: "특공" },
  { key: "spdF" as const, label: "특방" },
  { key: "spd" as const, label: "스피드" },
];

export const CATEGORY_KO: Record<string, string> = {
  Physical: "물리",
  Special: "특수",
  Status: "변화",
};

export const EVO_KO: Record<string, string> = {
  Level: "레벨",
  Item: "도구",
  Trade: "통신교환",
  TradeItem: "도구교환",
  Happiness: "친밀도",
  HappinessDay: "친밀도(낮)",
  HappinessNight: "친밀도(밤)",
  LevelMale: "레벨(수컷)",
  LevelFemale: "레벨(암컷)",
  LevelDay: "레벨(낮)",
  LevelNight: "레벨(밤)",
  AttackGreater: "공격>방어",
  AtkDefEqual: "공격=방어",
  DefenseGreater: "방어>공격",
  Location: "장소",
  HasMove: "기술보유",
  HasInParty: "파티보유",
  LevelRain: "비오는날 레벨",
  LevelWalk: "일정 걸음 레벨",
  LevelUseMoveCount: "기술 사용 횟수",
  LevelRecoilDamage: "반동 누적",
  LevelDarkInParty: "악타입 파티",
  LevelEvening: "저녁 레벨",
  HoldItem: "도구 소지",
  DayHoldItem: "낮 도구소지",
  NightHoldItem: "밤 도구소지",
  ItemMale: "도구(수컷)",
  ItemFemale: "도구(암컷)",
  ItemNight: "도구(밤)",
  HappinessMoveType: "친밀도+타입기술",
  LocationFlag: "장소 플래그",
  CollectItems: "도구 수집",
  BattleDealCriticalHit: "급소 배틀",
  Event: "이벤트",
  Silcoon: "실쿤",
  Cascoon: "카스쿤",
  Ninjask: "아이스크",
  Shedinja: "껍질몬",
  Beauty: "아름다움",
  None: "없음",
};

export const FUNCTION_CODES: { code: string; label: string }[] = [
  { code: "None", label: "부가효과 없음 (데미지만)" },
  { code: "SleepTarget", label: "상대를 잠들게 함" },
  { code: "PoisonTarget", label: "독을 남김" },
  { code: "BadlyPoisonTarget", label: "맹독" },
  { code: "BurnTarget", label: "화상을 남김" },
  { code: "ParalyzeTarget", label: "마비를 남김" },
  { code: "FreezeTarget", label: "얼림" },
  { code: "FlinchTarget", label: "풀죽게 함" },
  { code: "ConfuseTarget", label: "혼란" },
  { code: "BurnChance", label: "확률 화상" },
  { code: "ParalyzeChance", label: "확률 마비" },
  { code: "PoisonChance", label: "확률 독" },
  { code: "FreezeChance", label: "확률 얼음" },
  { code: "FlinchChance", label: "확률 풀죽음" },
  { code: "ConfuseChance", label: "확률 혼란" },
  { code: "LowerTargetAtk1", label: "상대 공격 1단계 하락" },
  { code: "LowerTargetDef1", label: "상대 방어 1단계 하락" },
  { code: "LowerTargetSpd1", label: "상대 스피드 1단계 하락" },
  { code: "LowerTargetSpa1", label: "상대 특공 1단계 하락" },
  { code: "LowerTargetSpdF1", label: "상대 특방 1단계 하락" },
  { code: "LowerTargetAcc1", label: "상대 명중 1단계 하락" },
  { code: "RaiseUserAtk1", label: "자신 공격 1단계 상승" },
  { code: "RaiseUserDef1", label: "자신 방어 1단계 상승" },
  { code: "RaiseUserSpd1", label: "자신 스피드 1단계 상승" },
  { code: "RaiseUserSpa1", label: "자신 특공 1단계 상승" },
  { code: "RaiseUserSpdF1", label: "자신 특방 1단계 상승" },
  { code: "RaiseUserAtk2", label: "자신 공격 2단계 상승" },
  { code: "RaiseUserSpd2", label: "자신 스피드 2단계 상승" },
  { code: "MultiHit", label: "2~5회 연속" },
  { code: "HitTwoTimes", label: "2회 연속" },
  { code: "RecoilThird", label: "반동 1/3" },
  { code: "RecoilFourth", label: "반동 1/4" },
  { code: "RecoilHalf", label: "반동 1/2" },
  { code: "HealUserHalfOfTotalHP", label: "최대 HP 절반 회복" },
  { code: "DrainTargetHPHalf", label: "준 데미지의 절반 흡수" },
  { code: "OHKO", label: "일격기" },
  { code: "AlwaysHit", label: "필중" },
  { code: "PriorityHit", label: "선공 (우선도 필드 사용)" },
  { code: "SwitchOutUser", label: "사용 후 교체" },
  { code: "FixedDamage", label: "고정 데미지" },
];

export const FLAG_HELP =
  "a=접촉  b=방어영향  e=스니치  f=거울  k=킹실드  n=가드교체";

export const ENCOUNTER_TYPE_KO: Record<string, string> = {
  Land: "풀숲",
  LandDay: "풀숲(낮)",
  LandNight: "풀숲(밤)",
  LandMorning: "풀숲(아침)",
  LandAfternoon: "풀숲(오후)",
  LandEvening: "풀숲(저녁)",
  Water: "물가",
  OldRod: "낡은낚싯대",
  GoodRod: "좋은낚싯대",
  SuperRod: "대단한낚싯대",
  Cave: "동굴",
  RockSmash: "바위깨기",
  HeadbuttLow: "박치기(약)",
  HeadbuttHigh: "박치기(강)",
  BugContest: "곤충채집",
};

export const SLOT_CHANCE_HINT: Record<string, number[]> = {
  Land: [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1],
  LandDay: [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1],
  LandNight: [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1],
  Cave: [20, 20, 10, 10, 10, 10, 5, 5, 4, 4, 1, 1],
  Water: [60, 30, 5, 4, 1],
  OldRod: [70, 30],
  GoodRod: [60, 20, 20],
  SuperRod: [40, 40, 15, 4, 1],
  RockSmash: [50, 35, 15],
};
