import type { Ability, Move, Species } from "./types.ts";
import { serializeMovesPbs, serializePokemonPbs } from "./pbs.ts";

function sp(
  id: number,
  internalName: string,
  name: string,
  types: string[],
  stats: [number, number, number, number, number, number],
  abilities: string[],
  hidden: string,
  moves: [number, string][],
  evo: [string, string, string][] = [],
  extra: Record<string, string> = {},
): Species {
  return {
    id,
    internalName,
    name,
    types,
    baseStats: {
      hp: stats[0],
      atk: stats[1],
      def: stats[2],
      spd: stats[3],
      spa: stats[4],
      spdF: stats[5],
    },
    abilities,
    hiddenAbility: hidden,
    levelMoves: moves.map(([level, move]) => ({ level, move })),
    tutorMoves: [],
    wildItems: [],
    evolutions: evo.map(([target, method, param]) => ({ target, method, param })),
    extra,
  };
}

function mv(
  id: number,
  internalName: string,
  name: string,
  type: string,
  category: Move["category"],
  power: number,
  accuracy: number,
  pp: number,
  functionCode: string,
  effectChance: number,
  description: string,
  extra: Partial<Move> = {},
): Move {
  return {
    id,
    internalName,
    name,
    type,
    category,
    power,
    accuracy,
    pp,
    functionCode,
    effectChance,
    priority: extra.priority ?? 0,
    flags: extra.flags ?? (category === "Status" ? "b" : "abef"),
    target: extra.target ?? "NearOther",
    description,
    extra: {},
  };
}

export const SAMPLE_ABILITIES: Ability[] = [
  { internalName: "OVERGROW", name: "심록", description: "HP가 줄면 풀 기술의 위력이 올라간다." },
  { internalName: "BLAZE", name: "맹화", description: "HP가 줄면 불꽃 기술의 위력이 올라간다." },
  { internalName: "TORRENT", name: "급류", description: "HP가 줄면 물 기술의 위력이 올라간다." },
  { internalName: "STATIC", name: "정전기", description: "접촉한 상대를 마비시킬 때가 있다." },
  { internalName: "LIGHTNINGROD", name: "피뢰침", description: "전기 기술을 끌어모아 특공을 올린다." },
  { internalName: "CHLOROPHYLL", name: "엽록소", description: "맑은 날 스피드가 올라간다." },
  { internalName: "SOLARPOWER", name: "선파워", description: "맑은 날 특공이 오르지만 HP가 줄어든다." },
  { internalName: "INTIMIDATE", name: "위협", description: "등장하면 상대의 공격을 떨어뜨린다." },
  { internalName: "GUTS", name: "근성", description: "상태 이상일 때 공격이 올라간다." },
  { internalName: "PROTEAN", name: "변환자재", description: "기술을 쓰면 그 타입으로 변한다." },
  { internalName: "LIBERO", name: "리베로", description: "기술을 쓰면 그 타입으로 변한다." },
  { internalName: "LONGREACH", name: "원격", description: "접촉 기술도 접촉하지 않은 것으로 친다." },
  { internalName: "TECHNICIAN", name: "테크니션", description: "위력 60 이하 기술의 위력이 올라간다." },
  { internalName: "ADAPTABILITY", name: "적응력", description: "자속 보정이 더 강해진다." },
  { internalName: "LEVITATE", name: "부유", description: "땅 타입 기술을 받지 않는다." },
  { internalName: "PRESSURE", name: "프레셔", description: "상대의 PP를 더 많이 줄인다." },
  { internalName: "INNERFOCUS", name: "정신력", description: "풀죽지 않는다." },
  { internalName: "SWIFTSSWIM", name: "쓱쓱", description: "비 오는 날 스피드가 올라간다." },
  { internalName: "SWIFTSWIM", name: "쓱쓱", description: "비 오는 날 스피드가 올라간다." },
  { internalName: "THICKFAT", name: "두꺼운지방", description: "불꽃·얼음 기술의 데미지를 줄인다." },
  { internalName: "CUTECHARM", name: "헤롱헤롱바디", description: "접촉한 상대를 헤롱헤롱하게 만들 때가 있다." },
  { internalName: "SYNCHRONIZE", name: "싱크로", description: "상태 이상을 상대에게 옮긴다." },
  { internalName: "TRACE", name: "트레이스", description: "상대의 특성을 복사한다." },
  { internalName: "TELEPATHY", name: "텔레파시", description: "아군의 공격을 받지 않는다." },
  { internalName: "MAGICGUARD", name: "매직가드", description: "공격 이외의 데미지를 입지 않는다." },
  { internalName: "FLASHFIRE", name: "타오르는불꽃", description: "불꽃 기술을 무효로 하고 위력을 올린다." },
  { internalName: "DROUGHT", name: "가뭄", description: "등장하면 날씨를 맑게 만든다." },
  { internalName: "DRIZZLE", name: "잔비", description: "등장하면 비를 내리게 한다." },
  { internalName: "SANDSTREAM", name: "모래날림", description: "등장하면 모래바람을 일으킨다." },
  { internalName: "SNOWWARNING", name: "눈퍼뜨리기", description: "등장하면 눈을 내리게 한다." },
  { internalName: "MOXIE", name: "자기과신", description: "상대를 쓰러뜨리면 공격이 올라간다." },
  { internalName: "SHEERFORCE", name: "우격다짐", description: "부가효과를 포기하고 위력을 올린다." },
  { internalName: "TINTEDLENS", name: "색안경", description: "효과가 별로인 기술의 위력을 올린다." },
  { internalName: "TINTED_LENS", name: "색안경", description: "효과가 별로인 기술의 위력을 올린다." },
  { internalName: "COMPOUNDEYES", name: "복안", description: "기술의 명중률이 올라간다." },
  { internalName: "KEENEYE", name: "날카로운눈", description: "명중률이 떨어지지 않는다." },
  { internalName: "RUNAWAY", name: "도주", description: "야생 포켓몬에게서 반드시 도망친다." },
  { internalName: "PICKUP", name: "픽업", description: "배틀이 끝나면 도구를 줍는다." },
  { internalName: "LIMBER", name: "유연", description: "마비되지 않는다." },
  { internalName: "BATTLEARMOR", name: "전투무장", description: "급소에 맞지 않는다." },
  { internalName: "STURDY", name: "옹골참", description: "한 방에 쓰러지지 않는다." },
  { internalName: "ROCKHEAD", name: "돌머리", description: "반동 데미지를 입지 않는다." },
  { internalName: "MULTISCALE", name: "멀티스케일", description: "HP가 가득일 때 데미지를 줄인다." },
  { internalName: "REGENERATOR", name: "재생력", description: "교체하면 HP를 조금 회복한다." },
];

export const SAMPLE_MOVES: Move[] = [
  mv(1, "TACKLE", "몸통박치기", "NORMAL", "Physical", 40, 100, 35, "None", 0, "온몸으로 상대에게 부딪쳐 공격한다."),
  mv(2, "GROWL", "울음소리", "NORMAL", "Status", 0, 100, 40, "LowerTargetAtk1", 100, "귀여운 울음소리로 상대의 공격을 떨어뜨린다.", { flags: "b" }),
  mv(3, "SCRATCH", "할퀴기", "NORMAL", "Physical", 40, 100, 35, "None", 0, "단단한 발톱으로 상대를 할퀴어 공격한다."),
  mv(4, "LEER", "째려보기", "NORMAL", "Status", 0, 100, 30, "LowerTargetDef1", 100, "날카로운 눈초리로 상대의 방어를 떨어뜨린다.", { flags: "b" }),
  mv(5, "EMBER", "불꽃세례", "FIRE", "Special", 40, 100, 25, "BurnChance", 10, "작은 불꽃을 상대에게 발사한다. 화상 상태가 될 때가 있다."),
  mv(6, "WATERGUN", "물대포", "WATER", "Special", 40, 100, 25, "None", 0, "물을 상대에게 발사하여 공격한다.", { flags: "bef" }),
  mv(7, "VINEWHIP", "덩굴채찍", "GRASS", "Physical", 45, 100, 25, "None", 0, "채찍처럼 휘감아 공격한다."),
  mv(8, "LEAFAGE", "나뭇잎", "GRASS", "Physical", 40, 100, 40, "None", 0, "나뭇잎을 상대에게 부딪친다."),
  mv(9, "POUND", "막치기", "NORMAL", "Physical", 40, 100, 35, "None", 0, "긴 꼬리나 손 등으로 상대를 때려 공격한다."),
  mv(10, "QUICKATTACK", "전광석화", "NORMAL", "Physical", 40, 100, 30, "None", 0, "눈에 보이지 않는 굉장한 속도로 상대에게 돌진한다.", { priority: 1 }),
  mv(11, "THUNDERSHOCK", "전기쇼크", "ELECTRIC", "Special", 40, 100, 30, "ParalyzeChance", 10, "전기 자극을 상대에게 날린다. 마비 상태가 될 때가 있다.", { flags: "bef" }),
  mv(12, "THUNDERBOLT", "10만볼트", "ELECTRIC", "Special", 90, 100, 15, "ParalyzeChance", 10, "강한 전격을 상대에게 날린다. 마비 상태가 될 때가 있다.", { flags: "bef" }),
  mv(13, "THUNDERWAVE", "전기자석파", "ELECTRIC", "Status", 0, 90, 20, "ParalyzeTarget", 100, "약한 전격을 날려 상대를 마비시킨다.", { flags: "b" }),
  mv(14, "FLAMETHROWER", "화염방사", "FIRE", "Special", 90, 100, 15, "BurnChance", 10, "세찬 불꽃을 상대에게 발사한다. 화상 상태가 될 때가 있다.", { flags: "bef" }),
  mv(15, "SURF", "파도타기", "WATER", "Special", 90, 100, 15, "None", 0, "큰 파도로 자신의 주위에 있는 포켓몬을 공격한다.", { flags: "bef", target: "AllNearOthers" }),
  mv(16, "SOLARBEAM", "솔라빔", "GRASS", "Special", 120, 100, 10, "None", 0, "1턴째에 빛을 가득 모아 2턴째에 발사한다.", { flags: "bef" }),
  mv(17, "RAZORLEAF", "잎날가르기", "GRASS", "Physical", 55, 95, 25, "None", 0, "잎사귀를 날려 상대를 베어 공격한다. 급소에 맞기 쉽다."),
  mv(18, "BUBBLE", "거품", "WATER", "Special", 40, 100, 30, "LowerTargetSpd1", 10, "거품을 상대에게 부딪친다. 스피드가 떨어질 때가 있다.", { flags: "bef" }),
  mv(19, "WATERPULSE", "물의파동", "WATER", "Special", 60, 100, 20, "ConfuseChance", 20, "물의 진동을 상대에게 가하여 공격한다. 혼란시킬 때가 있다.", { flags: "bef" }),
  mv(20, "NIGHTSLASH", "깜짝베기", "DARK", "Physical", 70, 100, 15, "None", 0, "순간적으로 틈을 노려 베어 공격한다. 급소에 맞기 쉽다."),
  mv(21, "SHADOWBALL", "섀도볼", "GHOST", "Special", 80, 100, 15, "LowerTargetSpdF1", 20, "검은 그림자의 덩어리를 내던진다. 특방이 떨어질 때가 있다.", { flags: "bef" }),
  mv(22, "PSYCHIC", "사이코키네시스", "PSYCHIC", "Special", 90, 100, 10, "LowerTargetSpdF1", 10, "강한 염동력을 상대에게 보내어 공격한다.", { flags: "bef" }),
  mv(23, "ICEBEAM", "냉동빔", "ICE", "Special", 90, 100, 10, "FreezeChance", 10, "냉동빔을 상대에게 발사한다. 얼음 상태가 될 때가 있다.", { flags: "bef" }),
  mv(24, "BLIZZARD", "눈보라", "ICE", "Special", 110, 70, 5, "FreezeChance", 10, "세찬 눈보라를 상대에게 내뿜는다.", { flags: "bef" }),
  mv(25, "EARTHQUAKE", "지진", "GROUND", "Physical", 100, 100, 10, "None", 0, "지진의 충격으로 자신의 주위에 있는 포켓몬을 공격한다.", { flags: "e", target: "AllNearOthers" }),
  mv(26, "STONEEDGE", "스톤에지", "ROCK", "Physical", 100, 80, 5, "None", 0, "뾰족한 바위를 상대에게 꿰뚫는다. 급소에 맞기 쉽다."),
  mv(27, "CLOSECOMBAT", "인파이트", "FIGHTING", "Physical", 120, 100, 5, "None", 0, "방심하고 혼신의 힘으로 공격한다. 자신의 방어와 특방이 떨어진다."),
  mv(28, "AERIALACE", "제비반환", "FLYING", "Physical", 60, 0, 20, "AlwaysHit", 0, "빠른 속도로 상대를 농락하여 벤다. 공격은 반드시 명중한다."),
  mv(29, "BRAVEBIRD", "브레이브버드", "FLYING", "Physical", 120, 100, 15, "RecoilThird", 0, "날개를 접어 저공비행으로 돌격한다. 자신도 데미지를 입는다."),
  mv(30, "DRACOMETEOR", "용성군", "DRAGON", "Special", 130, 90, 5, "None", 0, "하늘의 성스러운 힘을 상대에게 떨어뜨린다. 자신의 특공이 크게 떨어진다.", { flags: "bef" }),
  mv(31, "DARKPULSE", "악의파동", "DARK", "Special", 80, 100, 15, "FlinchChance", 20, "악의 아우라를 내뿜는다. 상대를 풀죽게 만들 때가 있다.", { flags: "bef" }),
  mv(32, "MOONBLAST", "문포스", "FAIRY", "Special", 95, 100, 15, "LowerTargetSpa1", 30, "달의 힘을 빌려 상대를 공격한다. 특공이 떨어질 때가 있다.", { flags: "bef" }),
  mv(33, "DAZZLINGGLEAM", "매지컬샤인", "FAIRY", "Special", 80, 100, 10, "None", 0, "강력한 빛을 내어 상대를 공격한다.", { flags: "bef", target: "AllNearOthers" }),
  mv(34, "IRONTAIL", "아이언테일", "STEEL", "Physical", 100, 75, 15, "LowerTargetDef1", 30, "단단한 꼬리로 때려부순다. 방어가 떨어질 때가 있다."),
  mv(35, "FLASHCANNON", "러스터캐논", "STEEL", "Special", 80, 100, 10, "LowerTargetSpdF1", 10, "빛의 덩어리를 상대에게 발사한다.", { flags: "bef" }),
  mv(36, "SLUDGEBOMB", "오물폭탄", "POISON", "Special", 90, 100, 10, "PoisonChance", 30, "더러운 오물을 상대에게 내던진다. 독 상태가 될 때가 있다.", { flags: "bef" }),
  mv(37, "TOXIC", "맹독", "POISON", "Status", 0, 90, 10, "BadlyPoisonTarget", 100, "상대를 맹독 상태로 만든다.", { flags: "b" }),
  mv(38, "SWORDSDANCE", "칼춤", "NORMAL", "Status", 0, 0, 20, "RaiseUserAtk2", 100, "싸움의 춤을 추며 기세를 높여 공격을 크게 올린다.", { flags: "b", target: "User" }),
  mv(39, "CALMMIND", "명상", "PSYCHIC", "Status", 0, 0, 20, "None", 0, "마음을 가라앉혀 특공과 특방을 올린다.", { flags: "b", target: "User" }),
  mv(40, "RECOVER", "HP회복", "NORMAL", "Status", 0, 0, 5, "HealUserHalfOfTotalHP", 100, "체력을 최대 HP의 절반만큼 회복한다.", { flags: "b", target: "User" }),
  mv(41, "PROTECT", "방어", "NORMAL", "Status", 0, 0, 10, "None", 0, "상대의 공격을 받지 않는다. 연속으로 쓰면 실패하기 쉽다.", { flags: "", target: "User", priority: 4 }),
  mv(42, "SUBSTITUTE", "대타출동", "NORMAL", "Status", 0, 0, 10, "None", 0, "자신의 HP를 조금 깎아 분신을 만든다.", { flags: "b", target: "User" }),
  mv(43, "U_TURN", "유턴", "BUG", "Physical", 70, 100, 20, "SwitchOutUser", 0, "공격한 뒤 다른 포켓몬과 교체한다."),
  mv(44, "VOLTSWITCH", "볼트체인지", "ELECTRIC", "Special", 70, 100, 20, "SwitchOutUser", 0, "공격한 뒤 다른 포켓몬과 교체한다.", { flags: "bef" }),
  mv(45, "LEAFSTORM", "리프스톰", "GRASS", "Special", 130, 90, 5, "None", 0, "날카로운 잎으로 상대를 둘러싼다. 자신의 특공이 크게 떨어진다.", { flags: "bef" }),
  mv(46, "GIGAIMPACT", "기가임팩트", "NORMAL", "Physical", 150, 90, 5, "None", 0, "모든 힘을 상대에게 부딪친다. 다음 턴은 움직일 수 없다."),
  mv(47, "HYPERBEAM", "파괴광선", "NORMAL", "Special", 150, 90, 5, "None", 0, "강한 광선을 상대에게 발사한다. 다음 턴은 움직일 수 없다.", { flags: "bef" }),
  mv(48, "DOUBLEKICK", "두번치기", "FIGHTING", "Physical", 30, 100, 30, "HitTwoTimes", 0, "2개의 다리로 상대를 걷어차 공격한다. 2회 연속으로 쓴다."),
  mv(49, "PINMISSILE", "바늘미사일", "BUG", "Physical", 25, 95, 20, "MultiHit", 0, "날카로운 침을 상대에게 발사하여 2~5회 연속으로 쓴다.", { flags: "bef" }),
  mv(50, "SLEEPPOWDER", "수면가루", "GRASS", "Status", 0, 75, 15, "SleepTarget", 100, "잠이 오는 가루를 상대에게 잔뜩 뿌려 잠들게 한다.", { flags: "b" }),
  mv(51, "FLOWERTRICK", "트릭플라워", "GRASS", "Physical", 70, 0, 10, "AlwaysHit", 0, "장식한 꽃다발로 공격한다. 반드시 명중하고 급소에 맞기 쉽다."),
  mv(52, "PYROBALL", "화염볼", "FIRE", "Physical", 120, 90, 5, "BurnChance", 10, "작은 돌을 발로 차 불타는 볼로 만든다."),
  mv(53, "WATERSHURIKEN", "물수리검", "WATER", "Special", 15, 100, 20, "MultiHit", 0, "점액으로 만든 수리검으로 2~5회 연속 공격한다. 반드시 선제 공격할 수 있다.", { priority: 1, flags: "bef" }),
  mv(54, "SUCKERPUNCH", "기습", "DARK", "Physical", 70, 100, 5, "None", 0, "상대보다 먼저 공격한다. 상대가 공격 기술을 쓰지 않으면 실패한다.", { priority: 1 }),
  mv(55, "NASTYPLOT", "나쁜음모", "DARK", "Status", 0, 0, 20, "None", 0, "나쁜 일을 생각해서 머리를 자극해 특공을 크게 올린다.", { flags: "b", target: "User" }),
  mv(56, "SPIRITSHACKLE", "그림자꿰매기", "GHOST", "Physical", 80, 100, 10, "None", 0, "상대의 그림자를 꿰매어 공격한다. 상대는 도망칠 수 없게 된다.", { flags: "bef" }),
];

export const SAMPLE_SPECIES: Species[] = [
  sp(1, "BULBASAUR", "이상해씨", ["GRASS", "POISON"], [45, 49, 49, 45, 65, 65], ["OVERGROW"], "CHLOROPHYLL",
    [[1, "TACKLE"], [1, "GROWL"], [7, "VINEWHIP"], [13, "RAZORLEAF"], [20, "SLEEPPOWDER"], [32, "SLUDGEBOMB"], [45, "SOLARBEAM"]],
    [["IVYSAUR", "Level", "16"]], { GrowthRate: "Parabolic", BaseEXP: "64", Rareness: "45" }),
  sp(2, "IVYSAUR", "이상해풀", ["GRASS", "POISON"], [60, 62, 63, 60, 80, 80], ["OVERGROW"], "CHLOROPHYLL",
    [[1, "TACKLE"], [1, "GROWL"], [7, "VINEWHIP"], [13, "RAZORLEAF"], [20, "SLEEPPOWDER"], [39, "SLUDGEBOMB"], [50, "SOLARBEAM"]],
    [["VENUSAUR", "Level", "32"]]),
  sp(3, "VENUSAUR", "이상해꽃", ["GRASS", "POISON"], [80, 82, 83, 80, 100, 100], ["OVERGROW"], "CHLOROPHYLL",
    [[1, "VINEWHIP"], [1, "GROWL"], [13, "RAZORLEAF"], [20, "SLEEPPOWDER"], [39, "SLUDGEBOMB"], [53, "SOLARBEAM"], [60, "LEAFSTORM"]]),
  sp(4, "CHARMANDER", "파이리", ["FIRE"], [39, 52, 43, 65, 60, 50], ["BLAZE"], "SOLARPOWER",
    [[1, "SCRATCH"], [1, "GROWL"], [7, "EMBER"], [16, "FLAMETHROWER"], [40, "GIGAIMPACT"]],
    [["CHARMELEON", "Level", "16"]]),
  sp(5, "CHARMELEON", "리자드", ["FIRE"], [58, 64, 58, 80, 80, 65], ["BLAZE"], "SOLARPOWER",
    [[1, "SCRATCH"], [7, "EMBER"], [20, "FLAMETHROWER"], [48, "GIGAIMPACT"]],
    [["CHARIZARD", "Level", "36"]]),
  sp(6, "CHARIZARD", "리자몽", ["FIRE", "FLYING"], [78, 84, 78, 100, 109, 85], ["BLAZE"], "SOLARPOWER",
    [[1, "EMBER"], [1, "SCRATCH"], [20, "FLAMETHROWER"], [36, "AERIALACE"], [54, "BRAVEBIRD"], [62, "GIGAIMPACT"]]),
  sp(7, "SQUIRTLE", "꼬부기", ["WATER"], [44, 48, 65, 43, 50, 64], ["TORRENT"], "SWIFTSWIM",
    [[1, "TACKLE"], [1, "TAILWHIP".replace("TAILWHIP", "GROWL")], [8, "WATERGUN"], [15, "WATERPULSE"], [33, "SURF"]],
    [["WARTORTLE", "Level", "16"]]),
  sp(8, "WARTORTLE", "어니부기", ["WATER"], [59, 63, 80, 58, 65, 80], ["TORRENT"], "SWIFTSWIM",
    [[1, "TACKLE"], [8, "WATERGUN"], [15, "WATERPULSE"], [40, "SURF"]],
    [["BLASTOISE", "Level", "36"]]),
  sp(9, "BLASTOISE", "거북왕", ["WATER"], [79, 83, 100, 78, 85, 105], ["TORRENT"], "SWIFTSWIM",
    [[1, "WATERGUN"], [15, "WATERPULSE"], [40, "SURF"], [56, "HYPERBEAM"], [62, "ICEBEAM"]]),
  sp(25, "PIKACHU", "피카츄", ["ELECTRIC"], [35, 55, 40, 90, 50, 50], ["STATIC"], "LIGHTNINGROD",
    [[1, "QUICKATTACK"], [1, "GROWL"], [4, "THUNDERSHOCK"], [15, "THUNDERWAVE"], [26, "THUNDERBOLT"], [45, "VOLTSWITCH"]],
    [["RAICHU", "Item", "THUNDERSTONE"]]),
  sp(26, "RAICHU", "라이츄", ["ELECTRIC"], [60, 90, 55, 110, 90, 80], ["STATIC"], "LIGHTNINGROD",
    [[1, "THUNDERSHOCK"], [1, "QUICKATTACK"], [1, "THUNDERBOLT"], [1, "THUNDERWAVE"]]),
  sp(94, "GENGAR", "팬텀", ["GHOST", "POISON"], [60, 65, 60, 110, 130, 75], ["LEVITATE"], "LEVITATE",
    [[1, "SHADOWBALL"], [1, "SLUDGEBOMB"], [1, "SUCKERPUNCH"], [12, "TOXIC"], [28, "DARKPULSE"], [40, "NASTYPLOT"], [48, "SHADOWBALL"]]),
  sp(130, "GYARADOS", "갸라도스", ["WATER", "FLYING"], [95, 125, 79, 81, 60, 100], ["INTIMIDATE"], "MOXIE",
    [[1, "TACKLE"], [20, "BITE".replace("BITE", "LEER")], [25, "WATERPULSE"], [32, "SURF"], [41, "ICEBEAM"], [52, "HYPERBEAM"], [60, "EARTHQUAKE"]]),
  sp(133, "EEVEE", "이브이", ["NORMAL"], [55, 55, 50, 55, 45, 65], ["RUNAWAY", "ADAPTABILITY"], "ANTICIPATION".replace("ANTICIPATION", "CUTECHARM"),
    [[1, "TACKLE"], [1, "GROWL"], [10, "QUICKATTACK"], [20, "BITE".replace("BITE", "TACKLE")], [33, "GIGAIMPACT"]],
    [
      ["VAPOREON", "Item", "WATERSTONE"],
      ["JOLTEON", "Item", "THUNDERSTONE"],
      ["FLAREON", "Item", "FIRESTONE"],
    ]),
  sp(134, "VAPOREON", "샤미드", ["WATER"], [130, 65, 60, 65, 110, 95], ["WATERABSORB".replace("WATERABSORB", "TORRENT")], "HYDRATION".replace("HYDRATION", "SWIFTSWIM"),
    [[1, "WATERGUN"], [1, "TACKLE"], [20, "WATERPULSE"], [33, "SURF"], [45, "ICEBEAM"], [50, "RECOVER"]]),
  sp(135, "JOLTEON", "쥬피썬더", ["ELECTRIC"], [65, 65, 60, 130, 110, 95], ["VOLTABSORB".replace("VOLTABSORB", "STATIC")], "QUICKFEET".replace("QUICKFEET", "LIGHTNINGROD"),
    [[1, "THUNDERSHOCK"], [1, "QUICKATTACK"], [20, "THUNDERWAVE"], [33, "THUNDERBOLT"], [45, "VOLTSWITCH"], [50, "PINMISSILE"]]),
  sp(136, "FLAREON", "부스터", ["FIRE"], [65, 130, 60, 65, 95, 110], ["FLASHFIRE"], "GUTS",
    [[1, "EMBER"], [1, "TACKLE"], [20, "QUICKATTACK"], [33, "FLAMETHROWER"], [45, "GIGAIMPACT"]]),
  sp(149, "DRAGONITE", "망나뇽", ["DRAGON", "FLYING"], [91, 134, 95, 80, 100, 100], ["INNERFOCUS"], "MULTISCALE",
    [[1, "TACKLE"], [20, "AERIALACE"], [35, "AQUATAIL".replace("AQUATAIL", "SURF")], [41, "DRACOMETEOR"], [50, "HYPERBEAM"], [61, "OUTRAGE".replace("OUTRAGE", "GIGAIMPACT")]]),
  sp(150, "MEWTWO", "뮤츠", ["PSYCHIC"], [106, 110, 90, 130, 154, 90], ["PRESSURE"], "UNNERVE".replace("UNNERVE", "INNERFOCUS"),
    [[1, "PSYCHIC"], [1, "SHADOWBALL"], [1, "RECOVER"], [22, "CALMMIND"], [40, "AURASPHERE".replace("AURASPHERE", "CLOSECOMBAT")], [50, "PSYCHIC"], [70, "HYPERBEAM"]]),
  sp(151, "MEW", "뮤", ["PSYCHIC"], [100, 100, 100, 100, 100, 100], ["SYNCHRONIZE"], "SYNCHRONIZE",
    [[1, "POUND"], [10, "PSYCHIC"], [20, "CALMMIND"], [30, "SHADOWBALL"], [40, "AURA".replace("AURA", "DAZZLINGGLEAM")], [50, "RECOVER"], [70, "HYPERBEAM"]]),
  sp(197, "UMBREON", "블래키", ["DARK"], [95, 65, 110, 65, 60, 130], ["SYNCHRONIZE"], "INNERFOCUS",
    [[1, "TACKLE"], [1, "GROWL"], [20, "DARKPULSE"], [33, "TOXIC"], [40, "MOONBLAST"], [50, "RECOVER"]]),
  sp(282, "GARDEVOIR", "가디안", ["PSYCHIC", "FAIRY"], [68, 65, 65, 80, 125, 115], ["SYNCHRONIZE", "TRACE"], "TELEPATHY",
    [[1, "GROWL"], [1, "POUND"], [18, "PSYCHIC"], [26, "DAZZLINGGLEAM"], [34, "CALMMIND"], [48, "MOONBLAST"], [56, "HYPERBEAM"]]),
  sp(448, "LUCARIO", "루카리오", ["FIGHTING", "STEEL"], [70, 110, 70, 90, 115, 70], ["STEADFAST".replace("STEADFAST", "INNERFOCUS"), "INNERFOCUS"], "JUSTIFIED".replace("JUSTIFIED", "GUTS"),
    [[1, "QUICKATTACK"], [1, "METALCLAW".replace("METALCLAW", "SCRATCH")], [12, "DOUBLEKICK"], [24, "FLASHCANNON"], [36, "CLOSECOMBAT"], [48, "SWORDSDANCE"], [60, "GIGAIMPACT"]]),
  sp(658, "GRENINJA", "개굴닌자", ["WATER", "DARK"], [72, 95, 67, 122, 103, 71], ["TORRENT"], "PROTEAN",
    [[1, "POUND"], [1, "GROWL"], [5, "WATERGUN"], [14, "QUICKATTACK"], [21, "WATERPULSE"], [33, "NIGHTSLASH"], [42, "WATERSHURIKEN"], [56, "SURF"], [70, "HYDROPUMP".replace("HYDROPUMP", "DARKPULSE")]],
    [], { Kind: "시노비포켓몬", Pokedex: "수행을 쌓아 닌자의 경지에 도달했다. 물로 만든 수리검은 철판도 가른다." }),
  sp(724, "DECIDUEYE", "모부기로", ["GRASS", "GHOST"], [78, 107, 75, 70, 100, 100], ["OVERGROW"], "LONGREACH",
    [[1, "TACKLE"], [1, "GROWL"], [1, "LEAFAGE"], [16, "RAZORLEAF"], [28, "SUCKERPUNCH"], [36, "SPIRITSHACKLE"], [48, "LEAFSTORM"], [55, "BRAVEBIRD"]]),
  sp(813, "SCORBUNNY", "염버니", ["FIRE"], [50, 71, 40, 69, 40, 40], ["BLAZE"], "LIBERO",
    [[1, "TACKLE"], [1, "GROWL"], [6, "EMBER"], [12, "QUICKATTACK"], [24, "DOUBLEKICK"], [36, "FLAMETHROWER"]],
    [["RABOOT", "Level", "16"]], { Kind: "토끼포켓몬" }),
  sp(814, "RABOOT", "래비풋", ["FIRE"], [65, 86, 60, 94, 55, 60], ["BLAZE"], "LIBERO",
    [[1, "TACKLE"], [6, "EMBER"], [12, "QUICKATTACK"], [24, "DOUBLEKICK"], [36, "FLAMETHROWER"], [48, "PYROBALL"]],
    [["CINDERACE", "Level", "35"]]),
  sp(815, "CINDERACE", "에이스번", ["FIRE"], [80, 116, 75, 119, 65, 75], ["BLAZE"], "LIBERO",
    [[1, "EMBER"], [1, "QUICKATTACK"], [12, "DOUBLEKICK"], [24, "U_TURN"], [38, "PYROBALL"], [54, "GIGAIMPACT"], [62, "FLAMETHROWER"]]),
  sp(906, "SPRIGATITO", "나오하", ["GRASS", "DARK"], [40, 61, 54, 65, 45, 45], ["OVERGROW"], "PROTEAN",
    [[1, "SCRATCH"], [1, "GROWL"], [7, "LEAFAGE"], [13, "QUICKATTACK"], [18, "BITE".replace("BITE", "SUCKERPUNCH")], [25, "NIGHTSLASH"]],
    [["FLORAGATO", "Level", "16"]], { Kind: "풀고양이포켓몬", Pokedex: "어나더레드 스타팅. 풀과 악 타입을 함께 지닌다. 변환자재로 타입을 바꿔 싸운다." }),
  sp(907, "FLORAGATO", "나로테", ["GRASS", "DARK"], [61, 80, 63, 83, 60, 63], ["OVERGROW"], "PROTEAN",
    [[1, "SCRATCH"], [7, "LEAFAGE"], [13, "QUICKATTACK"], [20, "SUCKERPUNCH"], [28, "NIGHTSLASH"], [38, "FLOWERTRICK"]],
    [["MEOWSCARADA", "Level", "36"]]),
  sp(908, "MEOWSCARADA", "마스카나", ["GRASS", "DARK"], [76, 110, 70, 123, 81, 70], ["OVERGROW"], "PROTEAN",
    [[1, "LEAFAGE"], [1, "SUCKERPUNCH"], [16, "NIGHTSLASH"], [28, "U_TURN"], [36, "FLOWERTRICK"], [48, "LEAFSTORM"], [56, "NASTYPLOT"]]),
  sp(656, "FROAKIE", "개굴마리", ["WATER"], [41, 56, 40, 71, 62, 44], ["TORRENT"], "PROTEAN",
    [[1, "POUND"], [1, "GROWL"], [5, "WATERGUN"], [10, "QUICKATTACK"], [21, "WATERPULSE"]],
    [["FROGADIER", "Level", "16"]]),
  sp(657, "FROGADIER", "개굴반장", ["WATER"], [54, 63, 52, 97, 83, 56], ["TORRENT"], "PROTEAN",
    [[1, "POUND"], [5, "WATERGUN"], [14, "QUICKATTACK"], [21, "WATERPULSE"], [33, "NIGHTSLASH"]],
    [["GRENINJA", "Level", "36"]]),
  sp(4481, "RIOLU", "리오르", ["FIGHTING"], [40, 70, 40, 60, 35, 40], ["STEADFAST".replace("STEADFAST", "INNERFOCUS"), "INNERFOCUS"], "PRANKSTER".replace("PRANKSTER", "GUTS"),
    [[1, "QUICKATTACK"], [1, "GROWL"], [8, "DOUBLEKICK"], [24, "SCREECH".replace("SCREECH", "LEER")], [32, "CLOSECOMBAT"]],
    [["LUCARIO", "Happiness", "220"]]),
];

// Fix Riolu id - I used 4481 by mistake. Should be 447.
SAMPLE_SPECIES[SAMPLE_SPECIES.length - 1]!.id = 447;
SAMPLE_SPECIES[SAMPLE_SPECIES.length - 1]!.internalName = "RIOLU";

const sprigSample = SAMPLE_SPECIES.find((s) => s.internalName === "SPRIGATITO");
if (sprigSample) sprigSample.tutorMoves = ["U_TURN", "GIGADRAIN", "ENERGYBALL", "ACROBATICS", "GRASSKNOT"];

export function buildSampleWorkspace() {
  const species = SAMPLE_SPECIES;
  const moves = SAMPLE_MOVES;
  return {
    species,
    moves,
    abilities: SAMPLE_ABILITIES,
    originalPokemonText: serializePokemonPbs(species),
    originalMovesText: serializeMovesPbs(moves),
    sourceLabel: "샘플 데이터 (어나더레드 스타일 스타팅 포함)",
  };
}
